model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
approval_policy = "on-request"
sandbox_mode = "danger-full-access"

[features]
web_search_request = true

[projects."/Users/travis/Downloads/submission"]
trust_level = "trusted"

[projects."/Users/travis/Library/CloudStorage/Dropbox/02_notes/obsidian-notes"]
trust_level = "trusted"

[projects."/Users/travis"]
trust_level = "trusted"

[projects."/Users/travis/Downloads/slides"]
trust_level = "trusted"

[projects."/Users/travis/Library/Mobile Documents/iCloud~com~nssurge~inc/Documents"]
trust_level = "trusted"

[projects."/Users/travis/00_code/llm-council"]
trust_level = "trusted"

[projects."/Users/travis/Library/CloudStorage/Dropbox/00_PhD/03-Curriculum/MAEG5080-smart-material/Smart_Materials_and_Structures_Course/01_Lecture_Notes"]
trust_level = "trusted"

[projects."/Users/travis/Library/CloudStorage/Dropbox/00_PhD/03-Curriculum/MAEG5080-smart-material/Smart_Materials_and_Structures_Course/02_Tutorials"]
trust_level = "trusted"

[projects."/Users/travis/Library/CloudStorage/Dropbox/00_PhD/01-2025/[00]-papers/NMI-TransCity/绘图/code"]
trust_level = "trusted"

[projects."/Users/travis/Library/CloudStorage/Dropbox/02_notes/obsidian-notes/.obsidian/snippets"]
trust_level = "trusted"

[projects."/Users/travis/Downloads"]
trust_level = "untrusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
